language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: deliver-ni
  api_key:
    secure: BdktvxVgCj1oKpajnch4ZZdF2sf/ffkx2dIl7htchuIi8wRo1Rfw82vMHu627aECl5cNrnGfZMYpZVqYfH/KkZLMuIi+IyatfdU9z2ktS8Ld4pWnTIjrL0CSwbWAbARUg62zt5c0so9SFNi6pxShUmeYSR7LsLjLTbkhtB/YpWG85h3m+Zm3t93Eizn8FZX3E4xZDvu7XniIpQfXl1lIhkjQY+yvwYOQUIIawgkEXwpLObFNHZqhHAConjrLR+KDLhqa/za6uNfJOQVqZyBgVkQRpdGLvDY5DxyHDwxbLiixMpsaQbKPt1vokb/wZFfu0DhE0gLqicY/rAyJO4sEc/09smnxmckK1YJSPEnYqGVhKP9YuMDqfgFlaL5puwture5VI2Vz11NGq7O1ly1bQhiyKvyi+9j3xErA4TbHSCUFdMNANG1znFmcbwEmCePQy5NbtIwbcRp1oz//yEsoJ7H6+vW/zMECoi1YpM5bfmZUbNJNaSdb/Gasf+dyDZopSWpw6Rh2x007CZjFYpR5Y80+VtnT8oDbP8svNIMMJxr21/ieWhg6B3OUAAqgMG7sasBGuc36BT8tPqTWZkw2st9geIQYGqGRJLOEbi4fzv4OeEthsASHTdk/CVuKOsT36AwhiRpdsKo61prgsRcpxH/bK5mhc5x8Yu4xeKaEXAA=
