language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: deliver-ni
  api_key:
    secure: "ZoE+AbGEo3n359v3SG7TUMBNv4GdF8FpGXmFILUMx8F8rIFrl4t5zFY0gN2ma9ITzK3Ny5+CiXqI/eltWrxVbdSQqjbMA3nIQSi1TWqqmpMSo1Ipr9pIP3NngeDE22OVwDEhIxwm+vgWQPAJ1JKuQR48WdqkkE6pYCf5SUC7fU+A1fuZwM2WCddEEqQungwirWYxnS29bwsTKETzfZKOygKktPZ8gq4be3i5mQKusr06EdywIda+VfPdrJRbqWykjXSTvS6R3str1Sm/pRk0P5RJLVfuPtZ5G/ODdcak/9fVukjxlaRSOxTJnSuDEB3Ax3S9aiXTmytpH8N4PZKmPzL0wCsNJQC4JHJl/8/Hs7AUu82QEUntLEGqzYuLU3Zuvxr8OdgC4io7ZfJEsnDapHkfZwQJke+wmTqcvYCZvF/wAfTAYccTrWLtjPwMRXDs31nMPaBh4bbq8TBLh7i9Wa20eIt95XcfUZq4tIMxV4XO/RcNtszH7e+9tBbH/rMPV6vB5ZbWnttAdu1AqKgyzBsAoQ6fswJEyopxnXVfGHHx6b/mVyfNHbyGQ13L4qSy1KaDVrNFC16yxVzAsY+DOZbCSOF8XomQvSUzRvhzZkBtC+lwnutlQ3O78qRAn/0IwemI6ISINc4CKAuu/UMVUP6TxAG933JuzqBK7LGZH4I="
