language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: deliver-ni
  api_key:
    secure: l+0EvPQObly/U8KBlM2wWiuPTVOYx+6TTBlMLabBGkEQ1tSIinVT/LxemNTRuFWdOo4V1DjUy+3XehhdLNFBJBw5WBRlg2cqU2WFbTKarIaa0WkG2oY5lhmc/Q3kaP4NvJ/btDImmxkgmfLPJ9Jnx3nCpkujjLmEB/14K7vML6eph0vMinLGbgyDxn7zwQmA3bkWnJmZoqeMzU0H/Ti0kXhQ3l28TCZg9QCDhnNawwsO6ZbJtQKR/TxoBfv1E/tsH+trg8fIn+MEDGUJWCKkGllyK2HYgNw3QvoS8vkmHkHSSswpt1EYgsjbj+HBvjydaJThB199l05W0FfG/+arFXeA6Tr2+bXuzCsEO7Q3SQ1y8PfSRAnGwYcbDVAbUFLJWPsH+Dba2n1TWE50BT1ibRfZjvUPRgcO/olON83iBxHCrXBxeYehAUnxHq7kKPIXNQso43/JFSTHEnXeKaHRDM4yojDAfM1D8pEO3EQy6vzFTIas492byPdDS4guTSoSXMjpumq/DGgpNe/H/7JEuxLNQCl9r2tsYAjCipXE8hToa1pPsw5SQryTWFXMePouyqkvxi9+z9rgtVaSwtwzgenvQgnTFCosCYztbQr65bqZRBA1tvvoS9t2Kp2x2FH2LrKTILBXgxrKZ+R3V0RSANi8AffoKRlnUBKvz6Y1Rlw=
